name: Forçar Cancelamento
on: workflow_dispatch # Permite rodar manualmente com o botão

# ISSO AQUI VAI DAR O PODER NECESSÁRIO PARA QUEBRAR O BLOQUEIO 403:
permissions:
  actions: write

jobs:
  cancelar:
    runs-on: ubuntu-latest
    steps:
      - name: Cancelar Workflow Travado
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X POST /repos/costtat/costtat.github.io/actions/runs/34838453419/force-cancel
