name: Forçar Cancelamento
on: workflow_dispatch # Permite rodar manualmente com o botão

permissions:
  actions: write

jobs:
  cancelar:
    runs-on: ubuntu-latest
    steps:
      - name: Deletar Registro do Workflow Travado
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X DELETE /repos/costtat/costtat.github.io/actions/runs/34838453419
